---
- hosts: local
  become: true
  tasks:
    - name: Install required components
      apt:
        name:
          - git
          - maven
          - openjdk-17-jdk
        state: present
    - name: Clone Maven Repo
      git:
        repo: https://github.com/training-support/FST_JUnit_Project.git
        dest: /home/sneha/FST_JUnit_Project
    - name: Run Maven Test
      command: mvn clean test
      args:
        chdir: /home/sneha/FST_JUnit_Project